version: '2'
services:

  # 公共镜像，只配置了国内镜像加速和中国时区配置
  alpine:
    build: alpine
    image: water/alpine

  mysql:
    build: mysql
    image: water/mysql
    depends_on:
      - "alpine"
    volumes:
      - "./volumes/mysql:/apps/mysql"
    ports:
      - "3306:3306"
    environment:
      # 默认的root密码和需要新建的数据库、用户名、密码，若需要重新设置，需要删除volumes/mysql/下面的全部内容，然后重新build
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=quoyle
      - MYSQL_PASSWORD=quoyle
    restart: always

  redis:
    build: redis
    image: redis-3.0
    depends_on:
      - "alpine"
    ports:
      - "6379:6379"
    restart: always
  
  mongodb:
    build: mongodb
    image: water/mongodb
    depends_on:
      - "alpine"
    ports:
      - "27017:27017"
      - "27018:27018"
    volumes:
      - "./volumes/mongodb:/data/db"
    restart: always

  nodejs:
    build: nodejs
    image: water/nodejs
    depends_on:
      - "alpine"
    links:
      - mysql
      - redis
      - mongodb
    ports:
      - "3000:3000"
    command: "tail -f /dev/null"
    volumes:
      - "./volumes/apps:/apps"
    restart: always

  # php5配置
  # phpfpm:
  #   build: phpfpm
  #   image: water/phpfpm
  #   depends_on:
  #     - "alpine"
  #   links:
  #     - mysql
  #     - redis
  #   volumes:
  #     - "./volumes/apps:/apps"
  #   restart: always

  # php7配置
  phpfpm7:
    build: phpfpm7
    image: water/phpfpm7
    depends_on:
      - "alpine"
    links:
      - mysql
      - redis
    volumes:
      - "./volumes/apps:/apps"
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254
    restart: always


  # 切换php版本时，请注意修改下面nginx相应的服务别名配置
  nginx:
    build: nginx
    image: water/nginx
    depends_on:
      - "alpine"
    links:
      - phpfpm7:phpfpm
    volumes_from:
      - phpfpm7
    volumes:
      - "./nginx/conf/conf.d:/etc/nginx/conf.d"
    ports:
      - "80:80"
      - "443:443"
    restart: always